### ISSUE TITLE
"resource limit exceeded" error message makes clear what limit and its value were exceeded

### ISSUE THREAD

**Issue by BigLep** [libp2p/go-libp2p-resource-manager#26]
## Done Criteria
When a "resource limit exceeded" error message is logged, it's self-service for someone looking at the logs to know the specific limit that was exceeded and what was the current limit value.

## Why Important
We need to make it more self-service for go-libp2p consumers to understand the limit that was exceeded and its value so they don't rely on go-libp2p maintainers and can navigate what they need to adjust rather than to defaulting to disabling the resource manager.   
 
## User/Customer
Developers of applications that consume go-libp2p.

## Notes
Currently we output a message like:

```
2022-05-25T13:56:29.298Z	DEBUG	rcmgr	go-libp2p-resource-manager@v0.2.1/scope.go:242	blocked memory reservation	
{
   "scope":"peer:12D3KooWFZy8PomPodoEGem4mKfGhENJTEcLfeXSk2DFSJR8zRnD",
   "size":262144,
   "priority":255,
   "stat":{
      "NumStreamsInbound":2,
      "NumStreamsOutbound":255,
      "NumConnsInbound":1,
      "NumConnsOutbound":0,
      "NumFD":1,
      "Memory":67108864
   },
   "error":"resource limit exceeded"
}
```

This tells us there was a "blocked memory reservation" for scope "peer:12D3KooWFZy8PomPodoEGem4mKfGhENJTEcLfeXSk2DFSJR8zRnD", but it doesn't tell us:
1. What is the specific config key that was exceeded.  This would be useful so one can quickly grep/search their code for where this value is set.
2. What the current value of the limit is.  This is important because limits can be set dynamically.  Even for static values, lets not make someone look up their code/configuration to understand the threshold value that was exceeded.  

I'm not saying this is the final copy (and I'm not up on the current config systax), but I  we'd want to say something like "reservation request for 262144 bytes of memory has been rejected with current value = 67108864 because of resource limit peer.12D3KooWFZy8PomPodoEGem4mKfGhENJTEcLfeXSk2DFSJR8zRnD.maxMemory=68000000"

**Comment by marten-seemann** [comment]
> 1. What is the specific config key that was exceeded. This would be useful so one can quickly grep/search their code for where this value is set.

I assume you're referring to the value in the [`DefaultLimitConfig`](https://pkg.go.dev/github.com/libp2p/go-libp2p-resource-manager#pkg-variables). That is _one way_ to configure the resource manager, but the general way (and the only information we have at the point this error message is generated) is that the value returned by the [`Limiter`](https://pkg.go.dev/github.com/libp2p/go-libp2p-resource-manager#Limiter) interface was too low.

We do know the scope though: It's `peer:12D3KooWFZy8PomPodoEGem4mKfGhENJTEcLfeXSk2DFSJR8zRnD`, so this is a peer scope. We should probably write up how to interpret scope names, and which sections in the `DefaultLimitConfig` they correspond to (that would be part of #27).

> 2. What the current value of the limit is. This is important because limits can be set dynamically. Even for static values, lets not make someone look up their code/configuration to understand the threshold value that was exceeded.

Done in https://github.com/libp2p/go-libp2p-resource-manager/pull/42.
