### ISSUE TITLE
Set data-driven default resource limits

### ISSUE THREAD

**Issue by BigLep** [libp2p/go-libp2p-resource-manager#32]
## Done Criteria
The [default resource limits](https://github.com/libp2p/go-libp2p-resource-manager/blob/master/limit_defaults.go) are data driven, which should prevent the resource manager from getting in the way unnecessarily.

## Why Important
Reduces the amount of friction for someone using go-libp2p with resource manager enabled by default. 

## User/Customer
Application developer using go-libp2p.

## Notes
1. Critical production usecases will likely still need to set their own limits per https://github.com/libp2p/go-libp2p-resource-manager/issues/28
2. Once we have profiles of what different production usecases need (e.g., ipfs.io gateway, filecoin bootstrapper) we can:
   1. Set more informed [static defaults](https://github.com/libp2p/go-libp2p-resource-manager/blob/master/limit_defaults.go)
   2. Give users different buckets (small, medium, large)
   3. Set limits dynamically based on system resources (e.g., determine amount of RAM, and then interpolate)
3. "design" should be done on the developer experience before we do implementation.

**Comment by BigLep** [comment]
Rather than focusing on data-driven static defaults, we're focused on having default limits that scale with available resources.  This is being worked on in https://github.com/libp2p/go-libp2p-resource-manager/pull/48

**Comment by MarcoPolo** [comment]
@marten-seemann can we close this?

**Comment by marten-seemann** [comment]
Yes. We might need to fine-tune our limits (and the corresponding increases) a bit in the future, but the general problem was solved.
